### ISSUE TITLE
Hook up TravisCI

### ISSUE THREAD

**Issue by naganowl** [mavenlink/kitno-loader#16]

**Comment by naganowl** [comment]
@racerpeter if you don't mind...

**Comment by racerpeter** [comment]
Does CircleCI work? If so then done!

**Comment by racerpeter** [comment]
[![CircleCI](https://circleci.com/gh/mavenlink/kitno-loader.svg?style=svg)](https://circleci.com/gh/mavenlink/kitno-loader)

**Comment by naganowl** [comment]
Didn't realize that our CircleCI supported public repos, thanks @racerpeter!
